version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"

  redis-client:
    image: redis:latest
    container_name: redis-client
    command: sh -c "while true; do sleep 1000; done"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

  postgres-client:
    image: postgres:latest
    container_name: postgres-client
    command: sh -c "while true; do sleep 1000; done"
    environment:
      PGPASSWORD: password

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  mysql-client:
    image: mysql:latest
    container_name: mysql-client
    command: sh -c "while true; do sleep 1000; done"

  dice:
    image: dicedb/dice-server
    container_name: dice-db
    ports:
      - "7379:7379"

  dice-cli:
    build: ./dicecli
    container_name: dice-cli
    working_dir: /app
    environment:
      HOST_TYPE: ${HOST_TYPE:-linux}
    #network_mode: "host" // # Uncomment this line if facing connectivity issues
    command: bash -c "while true; do sleep 3600; done"
